# Generated by Django 2.2.6 on 2019-11-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricpcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=3, default=0, max_digits=10000)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
