# Generated by Django 2.2.6 on 2019-11-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='descricpcion',
            new_name='descripcion',
        ),
    ]
