# Generated by Django 2.2.6 on 2019-11-24 03:38

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cuenta', models.CharField(max_length=11)),
                ('tipo_movimiento', multiselectfield.db.fields.MultiSelectField(choices=[('DB', 'Transacción Débito'), ('CR', 'Saldo a Favor del Contribuyente')], max_length=200)),
                ('fecha_asiento', models.DateField(null=True)),
                ('monto', models.DecimalField(decimal_places=3, default=0, max_digits=10000)),
                ('estado', models.BooleanField(default=True)),
                ('Clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Clientes')),
            ],
        ),
    ]
