# Generated by Django 2.2.6 on 2019-12-05 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Articulo', '0002_auto_20191109_1013'),
        ('Vendedores', '0001_initial'),
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturación',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('comentario', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=5000, default=0, max_digits=10000)),
                ('precio_unitario', models.DecimalField(decimal_places=3, default=0, max_digits=10000)),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articulo.Articulo')),
                ('Clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Clientes')),
                ('Vendeores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendedores.Vendedores')),
            ],
        ),
    ]
