# Generated by Django 2.2.6 on 2019-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.TextField(blank=True, null=True)),
                ('cedula', models.CharField(max_length=40, unique=True)),
                ('cuenta', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
